# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://example.com"

theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Boundless Forest"
author = "Pengfei Wang"
copyright = "Copyright © 2023, bear."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Record lifes and tech things"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  hideMadeWithLine = true
