
baseURL: "https://green-land.space"
theme: 'PaperMod'
paginate: 5

# Basic metadata configuration for your blog.
title: "Green Land"
author: "boundless-forest"
copyright: "Copyright © 2023, bear."
languageCode: "en-US"

enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          tag: tags
        menu:
            main:
                - name: Tags
                  url: tags/
                  weight: 10

params:
  env: production
  author: boundless-forest
  ShowReadingTime: true
  ShowShareButtons: false
  favicon: true
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShareButtons: ["linkedin", "twitter"]
  defaultTheme: light

  assets:
      disableHLJS: true
      favicon: "favicon.ico"
      favicon16x16:  "favicon-16x16.png"
      favicon32x32:  "favicon-32x32.png"