
baseURL: "https://example.com"
theme: 'PaperMod'
paginate: 5

# Basic metadata configuration for your blog.
title: "Green Land"
author: "boundless-forest"
copyright: "Copyright © 2023, bear."
languageCode: "en-US"

enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Tags
                  url: tags/
                  weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod
  ShowReadingTime: true
  ShowShareButtons: false
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShareButtons: ["linkedin", "twitter"]

  homeInfoParams:
        Title: "Who am I"
        Content: >
          As a programmer with a passion for reading, I have dedicated the past five years to honing my skills in blockchain technology, initially working with permissioned chains and later transitioning to permissionless. 
          In my day-to-day life, I am captivated by books, particularly those that explore history and society. These works inspire me and offer valuable insights into historical events. 
          I created this website to share my thoughts and ideas, with the hope that they may prove helpful to others.

  socialIcons:
    - name: "Github"
      url: "https://github.com/boundless-forest"
    - name: "twitter"
      url: "https://twitter.com/boundless87"